apiVersion: v1
kind: Pod
metadata:
  name: ofbiz
spec:
  containers:
    - image: gcr.io/ofbiz-1/ofbiz_v1
      name: ofbiz-image
      imagePullPolicy: Always
      ports:
        - containerPort: 8443, 8080
      volumeMounts:
          # Name must match the volume name below.
        - name: ofbiz-persistent-storage
          # Mount path within the container.
          mountPath: /var/ofbiz/data
  volumes:
    - name: ofbiz-persistent-storage
      gcePersistentDisk:
        # This GCE persistent disk must already exist.
        pdName: ofbiz-disk
        fsType: ext4
